In [4]:
# selection sort (very slow)
import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [6]:
x = np.array([2, 1, 4, 3, 5])
%timeit np.sort(x)

The slowest run took 9.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.31 µs per loop


In [8]:
%timeit x.sort

The slowest run took 30.37 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 91.5 ns per loop


In [12]:
# indices are stored as arguments
i = np.argsort(x)
print(i)

# use fancy indexing to construct the sorted array
x[i]

[1 0 3 2 4]


array([1, 2, 3, 4, 5])